INSERT INTO DBARCHETYPE01.USUARIO_LOGIN (USUALOGIN_ID,VERSAO_ENTIDADE,DATAHORA_CADASTRO,DATAHORA_MODIFICACAO,HABILITADO,USUALOGIN_NM_LOGIN,USUALOGIN_DS_SENHA,USUALOGIN_DS_SENHA_SALT) 
	VALUES (NEXTVAL('DBARCHETYPE01.SEQ_USUARIO'),0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,'11111111111','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
INSERT INTO DBARCHETYPE01.USUARIO_LOGIN (USUALOGIN_ID,VERSAO_ENTIDADE,DATAHORA_CADASTRO,DATAHORA_MODIFICACAO,HABILITADO,USUALOGIN_NM_LOGIN,USUALOGIN_DS_SENHA,USUALOGIN_DS_SENHA_SALT) 
	VALUES (NEXTVAL('DBARCHETYPE01.SEQ_USUARIO'),0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,'22222222222','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');

INSERT INTO ACESSO.PAPEL(ID_PAPEL, VERSAO_ENTIDADE, DATAHORA_CADASTRO, DATAHORA_MODIFICACAO,HABILITADO, LOGIN_USUARIO, DESCRICAO, NOME)
    VALUES (nextval('DBARCHETYPE01.SEQ_PAPEL'), 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,1, null, null, 'SystemAdmin');
INSERT INTO ACESSO.PAPEL(ID_PAPEL, VERSAO_ENTIDADE, DATAHORA_CADASTRO, DATAHORA_MODIFICACAO,HABILITADO, LOGIN_USUARIO, DESCRICAO, NOME)
    VALUES (nextval('DBARCHETYPE01.SEQ_PAPEL'), 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,1, null, null, 'Admin');
INSERT INTO ACESSO.PAPEL(ID_PAPEL, VERSAO_ENTIDADE, DATAHORA_CADASTRO, DATAHORA_MODIFICACAO,HABILITADO, LOGIN_USUARIO, DESCRICAO, NOME)
    VALUES (nextval('DBARCHETYPE01.SEQ_PAPEL'), 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,1, null, null, 'Usuario');

INSERT INTO DBARCHETYPE01.USUARIO_LOGIN_PAPEL (ID_USUARIO,ID_PAPEL) VALUES ((SELECT ID_USUARIO FROM DBARCHETYPE01.USUARIO WHERE LOGIN = '11111111111'),(SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'));

INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Usuario.list');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Usuario.insert');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Usuario.edit');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Usuario.view');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Usuario.remove');

INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Usuario.list'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Usuario.insert'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Usuario.edit'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Usuario.view'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Usuario.remove'));

INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Papel.list');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Papel.insert');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Papel.edit');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Papel.view');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Papel.remove');

INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Papel.list'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Papel.insert'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Papel.edit'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Papel.view'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Papel.remove'));

INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Certificado.list');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Certificado.insert');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Certificado.edit');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Certificado.view');
INSERT INTO DBARCHETYPE01.PERMISSAO (ID_PERMISSAO,NOME) VALUES (nextval('DBARCHETYPE01.SEQ_PERMISSAO'),'Certificado.remove');

INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Certificado.list'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Certificado.insert'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Certificado.edit'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Certificado.view'));
INSERT INTO DBARCHETYPE01.PAPEL_PERMISSAO (ID_PAPEL,ID_PERMISSAO) VALUES ((SELECT ID_PAPEL FROM DBARCHETYPE01.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERMISSAO FROM DBARCHETYPE01.PERMISSAO WHERE NOME = 'Certificado.remove'));
