//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-autocomplete/entity-auto-complete.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, OnInit, forwardRef } from '@angular/core';
import { EntityCompleteComponent } from '../../../framework/components/entity-auto-complete.component';
import { MessageService } from '../../../util/message.service';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { Filial } from '../filial';
import { FilialService } from '../filial.service';

export const FILIAL_AUTO_COMPLETE_CONTROL_VALUE_ACCESSOR: any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => FilialAutocompleteComponent),
  multi: true
};

@Component({
  selector: 'app-filial-autocomplete',
  templateUrl: './filial-autocomplete.component.html',
  styleUrls: ['./filial-autocomplete.component.scss'],
  providers: [FILIAL_AUTO_COMPLETE_CONTROL_VALUE_ACCESSOR]
})
export class FilialAutocompleteComponent extends EntityCompleteComponent<Filial, FilialService> {

  constructor(protected entityService: FilialService, protected messageService: MessageService) {
    super(entityService, messageService);
  }

}

