//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-detail/entity-detail.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, Input } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { AppEntityDetailComponent } from '../../../core/components/app-entity-detail.component';
import { ActivatedRoute, Router } from '@angular/router';
import { Location } from '@angular/common';
import { EnumeratorsService } from '../../enumerators.service';
import { EntityDetailComponent, MessageService } from 'framework-lib';

import { Parametro } from '../parametro';
import { ParametroService } from '../parametro.service';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-parametro-detail',
  templateUrl: './parametro-detail.component.html',
  styleUrls: ['./parametro-detail.component.scss']
})
export class ParametroDetailComponent extends
  AppEntityDetailComponent<Parametro, ParametroService> {


  tipoParametroValues: any[];

  constructor(
    protected route: ActivatedRoute,
    protected router: Router,
    protected messageService: MessageService,
    protected location: Location,
    protected translate: TranslateService,
    protected fb: FormBuilder,
    protected enumeratorsService: EnumeratorsService,
    protected entityService: ParametroService) {
    super(route, router, messageService, location, translate, fb, enumeratorsService, entityService, 'Parametro');
  }

  protected async loadEnumValues() {
    this.cacheEnums['TipoParametro'] = await this.enumeratorsService.getTipoParametroValues().toPromise();
  }

  protected loadEntityRelations(): void {
  }



}
