//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity.module.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatSortModule } from '@angular/material';
import { FileUploadModule } from 'primeng/fileupload';

import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { SharedModule } from '../../shared/shared.module';
import { RouterModule } from '@angular/router';

import { EntitiesModule } from '../entities.module';

import { ParametroListComponent } from './parametro-list/parametro-list.component';
import { ParametroDetailComponent } from './parametro-detail/parametro-detail.component';
import { ParametroAutocompleteComponent } from './parametro-autocomplete/parametro-autocomplete.component';
import { ParametroLineComponent } from './parametro-line/parametro-line.component';
import { ParametroRoutingModule } from './parametro-routing.module';

@NgModule({
  imports: [
    CommonModule,
    ParametroRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,

    MatSortModule,

	// Primeng
    FileUploadModule,

    EntitiesModule,
    
    SharedModule
  ],
  exports: [
    ParametroListComponent,
    ParametroDetailComponent,
    ParametroLineComponent,
    ParametroAutocompleteComponent
  ],
  declarations: [
  ]
})
export class ParametroModule { }
