//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity.datasource.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Parametro } from './parametro';
import { ParametroService } from './parametro.service';
import { EntityDataSource } from 'framework-lib';
import { Paginator } from 'framework-lib';
import { MatSort } from '@angular/material';

/**
 * Implementação da classe de serviço da entidade Parametro.
 */
export class ParametroDataSource extends EntityDataSource<Parametro, ParametroService> {

  constructor(public paginator: Paginator, public sort: MatSort, public entityService: ParametroService) {
    super(paginator, sort, entityService);
  }

}
