//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//

import { BaseEntity } from 'framework-lib';

export class Parametro extends BaseEntity {
    // Raw attributes
    descricao: string = null;
    valor: string = null;
    chave: string = null;
    dataHoraAlteracao: Date = null;
    tipoParametro: string = null;

    constructor(json?: any, depth?: number) {
        super(json, depth);
    }

    /**
     * Converter um array de json em um array de objetos.
     */
    static toArray(jsons: any[], depth?: number): Parametro[] {
        const entities: Parametro[] = [];
        if (jsons != null) {
            for (const json of jsons) {
              const entity = new Parametro();
              entity.loadFromJson(json, depth);
              entities.push(entity);
            }
        }
        return entities;
    }

    /**
     * Responsavel por carregar os campos
     */
    protected loadEntityFields(json?: any, depth?: number): void {
        super.loadEntityFields(json);
        this.descricao = json.descricao;
        this.valor = json.valor;
        this.chave = json.chave;
        if (json.dataHoraAlteracao != null) {
            this.dataHoraAlteracao = new Date(json.dataHoraAlteracao);
        }
        this.tipoParametro = json.tipoParametro;
        if (depth && depth-- > 0) {
        }
    }
}
