//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-detail/entity-detail.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, Input } from '@angular/core';
import { EntityDetailComponent } from '../../../framework/components/entity-detail.component';
import { ActivatedRoute, Router } from '@angular/router';
import { Location } from '@angular/common';
import { MessageService } from '../../../util/message.service';
import { EnumeratorsService } from '../../enumerators.service';

import { Filial } from '../filial';
import { FilialService } from '../filial.service';
import { Empresa } from '../../empresa/empresa';

@Component({
  selector: 'app-filial-detail',
  templateUrl: './filial-detail.component.html',
  styleUrls: ['./filial-detail.component.scss']
})
export class FilialDetailComponent extends EntityDetailComponent<Filial, FilialService> {


    @Input() // used to pass the parent when creating a new Filial
    set idEmpresa(idEmpresa: Empresa) {
        this.entity = this.entityService.newEntity();
        this.entity.idEmpresa = idEmpresa;
    }



    constructor(protected route: ActivatedRoute, protected router: Router, protected messageService: MessageService,
        protected location: Location,
        protected enumeratorsService: EnumeratorsService,
        protected entityService: FilialService) {
        super(route, router, messageService, location, enumeratorsService, entityService, 'Filial');
    }

    protected loadEnumValues(): void {
    }

    protected loadEntityRelations(): void {
    }

    public gotoIdEmpresa(): void {
        this.gotoEntity('empresa', this.entity.idEmpresa.id);
    }
    public clearIdEmpresa() {
        this.entity.idEmpresa = null;
    }



}


