//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-line/entity-line.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, OnInit, Input } from '@angular/core';
import { Parametro } from '../parametro';

@Component({
  selector: 'app-parametro-line',
  templateUrl: './parametro-line.component.html',
  styleUrls: ['./parametro-line.component.scss']
})
export class ParametroLineComponent implements OnInit {

  @Input() public entity: Parametro;

  constructor() { }

  ngOnInit() {
  }

}
