/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/util/DefaultMessageSource.p.vm.java
 */
package br.com.framework.piloto.core.util;

import static com.google.common.collect.Maps.newHashMap;

import java.text.MessageFormat;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.google.common.collect.Lists;

import br.com.framework.piloto.core.indexer.SolrIndexerService;

public class DefaultMessageSource implements MessageSource {

    protected Logger logger = LoggerFactory.getLogger(DefaultMessageSource.class);

    protected Map<String, Map<Locale, ResourceBundle>> resourceBundles = newHashMap();

    protected List<String> basenames = Lists.newArrayList();

    @Override
    public void setBasenames(String... basenames) {
        if (basenames != null && basenames.length > 0) {
            this.basenames.clear();
            this.basenames.addAll(Arrays.asList(basenames));
        }
    }

    @Override
    public String getMessage(String key, Locale locale) {
        return getMessage(key, null, locale);
    }

    @Override
    public String getMessage(String key, Object[] args, Locale locale) {
        if (key == null) {
            return "";
        }

        // NOTE: we do not use varargs, as passing var args from method to method does not work...        
        String messageFormat = getMessageFormatFromKey(key, locale);

        if (messageFormat != null) {
            if (args == null || args.length == 0) {
                return messageFormat;
            }

            switch (args.length) {
            case 1:
                return MessageFormat.format(messageFormat, args[0]);
            case 2:
                return MessageFormat.format(messageFormat, args[0], args[1]);
            case 3:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2]);
            case 4:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3]);
            case 5:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3], args[4]);
            case 6:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3], args[4], args[5]);
            case 7:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3], args[4], args[5], args[6]);
            case 8:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7]);
            case 9:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7], args[8]);
            case 10:
                return MessageFormat.format(messageFormat, args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7], args[8], args[9]);
            default:
                throw new IllegalStateException("need more case!");
            }
        } else {
            return "";
        }
    }

    protected String getMessageFormatFromKey(String key, Locale locale) {
        String messageFormat = null;
        for (String basename : basenames) {
            ResourceBundle resourceBundle = getResourceBundle(basename, locale);
            try {
                messageFormat = resourceBundle.getString(key);
            } catch (MissingResourceException e) {
            	logger.error("No message format from key " + basename, e);
                throw e;
            }
            if (messageFormat != null) {
                break;
            }
        }
        return messageFormat;
    }

    protected ResourceBundle getResourceBundle(String basename, Locale locale) {
        ResourceBundle resourceBundle = null;
        Map<Locale, ResourceBundle> basenameResourceBundle = resourceBundles.get(basename);
        if (basenameResourceBundle != null) {
            resourceBundle = basenameResourceBundle.get(locale);
        } else {
            resourceBundles.put(basename, new HashMap<Locale, ResourceBundle>());
        }

        if (resourceBundle == null) {
            try {
                resourceBundle = ResourceBundle.getBundle(basename, locale, this.getClass().getClassLoader(), new CustomResourceBundleControl());
            } catch (MissingResourceException e) {
                logger.error("No resource bundle file for %s", basename, e);
                throw e;
            }
            resourceBundles.get(basename).put(locale, resourceBundle);

        }

        return resourceBundle;
    }
}
