/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/domain/EntityMeta_.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.domain.meta;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import br.jus.framework.piloto.domain.Empresa;

@StaticMetamodel(Empresa.class)
public abstract class Empresa_ {

    // Raw attributes
    public static volatile SingularAttribute<Empresa, Long> id;
    public static volatile SingularAttribute<Empresa, Long> versaoEntidade;
    public static volatile SingularAttribute<Empresa, LocalDateTime> dhCriacao;
    public static volatile SingularAttribute<Empresa, LocalDateTime> dhModificacao;
    public static volatile SingularAttribute<Empresa, Integer> flHabilitado;
    public static volatile SingularAttribute<Empresa, String> nmLogin;
    public static volatile SingularAttribute<Empresa, String> codigo;
    public static volatile SingularAttribute<Empresa, String> nomeFantasia;
    public static volatile SingularAttribute<Empresa, String> razaoSocial;
    public static volatile SingularAttribute<Empresa, String> nmLoginAlteracao;
}