/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/domain/EntityMeta_.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.domain.meta;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import br.jus.framework.piloto.domain.Empresa;
import br.jus.framework.piloto.domain.Filial;

@StaticMetamodel(Filial.class)
public abstract class Filial_ {

    // Raw attributes
    public static volatile SingularAttribute<Filial, Long> id;
    public static volatile SingularAttribute<Filial, Long> versaoEntidade;
    public static volatile SingularAttribute<Filial, LocalDateTime> dhCriacao;
    public static volatile SingularAttribute<Filial, LocalDateTime> dhModificacao;
    public static volatile SingularAttribute<Filial, Integer> flHabilitado;
    public static volatile SingularAttribute<Filial, String> nmLogin;
    public static volatile SingularAttribute<Filial, String> codigo;
    public static volatile SingularAttribute<Filial, String> nomeFantasia;
    public static volatile SingularAttribute<Filial, String> razaoSocial;
    public static volatile SingularAttribute<Filial, String> nmLoginAlteracao;

    // Many to one
    public static volatile SingularAttribute<Filial, Empresa> idEmpresa;
}