/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/domain/EntityMeta_.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.domain.meta;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

import br.jus.framework.piloto.domain.Usuario;
import br.jus.framework.piloto.domain.enums.Status;

@StaticMetamodel(Usuario.class)
public abstract class Usuario_ {

    // Raw attributes
    public static volatile SingularAttribute<Usuario, Long> id;
    public static volatile SingularAttribute<Usuario, String> nome;
    public static volatile SingularAttribute<Usuario, String> login;
    public static volatile SingularAttribute<Usuario, String> password;
    public static volatile SingularAttribute<Usuario, String> email;
    public static volatile SingularAttribute<Usuario, Long> version;
    public static volatile SingularAttribute<Usuario, LocalDateTime> creationDate;
    public static volatile SingularAttribute<Usuario, LocalDateTime> lastModificationDate;
    public static volatile SingularAttribute<Usuario, String> creationAuthor;
    public static volatile SingularAttribute<Usuario, String> lastModificationAuthor;
    // Import enums
    public static volatile SingularAttribute<Usuario, Status> status;
    public static volatile SingularAttribute<Usuario, byte[]> fotoBinary;
    public static volatile SingularAttribute<Usuario, String> fotoFileName;
    public static volatile SingularAttribute<Usuario, String> fotoContentType;
    public static volatile SingularAttribute<Usuario, Long> fotoSize;
}