<#list entitiesMetamodel as entity>
-- Inserts das permissões para entidade ${entity.simpleName}
INSERT INTO ACESSO.PERMISSAO (ID_PERM, VERSAO_ENTIDADE,NOME) VALUES (nextval('ACESSO.SEQ_PERMISSAO'),0,'${entity.simpleName}.list');
INSERT INTO ACESSO.PERMISSAO (ID_PERM, VERSAO_ENTIDADE,NOME) VALUES (nextval('ACESSO.SEQ_PERMISSAO'),0,'${entity.simpleName}.insert');
INSERT INTO ACESSO.PERMISSAO (ID_PERM, VERSAO_ENTIDADE,NOME) VALUES (nextval('ACESSO.SEQ_PERMISSAO'),0,'${entity.simpleName}.edit');
INSERT INTO ACESSO.PERMISSAO (ID_PERM, VERSAO_ENTIDADE,NOME) VALUES (nextval('ACESSO.SEQ_PERMISSAO'),0,'${entity.simpleName}.view');
INSERT INTO ACESSO.PERMISSAO (ID_PERM, VERSAO_ENTIDADE,NOME) VALUES (nextval('ACESSO.SEQ_PERMISSAO'),0,'${entity.simpleName}.remove');

-- Associação com o Papel - SystemAdmin
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.list'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.insert'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.edit'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.view'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'SystemAdmin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.remove'));

-- Associação com o Papel - Admin
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'Admin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.list'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'Admin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.insert'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'Admin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.edit'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'Admin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.view'));
INSERT INTO ACESSO.PAPEL_PERM (ID_PAPEL,ID_PERM) VALUES ((SELECT ID_PAPEL FROM ACESSO.PAPEL WHERE NOME = 'Admin'), (SELECT ID_PERM FROM ACESSO.PERMISSAO WHERE NOME = '${entity.simpleName}.remove'));

</#list>

