//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entities.module.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { NgModule } from '@angular/core';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { MatSortModule } from '@angular/material';
import { CdkTableModule } from '@angular/cdk/table';
import { FileUploadModule } from 'primeng/fileupload';

import { NgSelectModule } from '@ng-select/ng-select';
import { NgxMaskModule } from 'ngx-mask';

import { SharedModule } from '../shared/shared.module';
import { EntitiesRoutingModule } from './entities-routing.module';
import { EntitiesComponent } from './entities.component';

import { DesafioListComponent } from './desafio/desafio-list/desafio-list.component';
import { DesafioDetailComponent } from './desafio/desafio-detail/desafio-detail.component';
import { DesafioLineComponent } from './desafio/desafio-line/desafio-line.component';
import { DesafioAutocompleteComponent } from './desafio/desafio-autocomplete/desafio-autocomplete.component';
import { HabitoListComponent } from './habito/habito-list/habito-list.component';
import { HabitoDetailComponent } from './habito/habito-detail/habito-detail.component';
import { HabitoLineComponent } from './habito/habito-line/habito-line.component';
import { HabitoAutocompleteComponent } from './habito/habito-autocomplete/habito-autocomplete.component';
import { RoleListComponent } from './role/role-list/role-list.component';
import { RoleDetailComponent } from './role/role-detail/role-detail.component';
import { RoleLineComponent } from './role/role-line/role-line.component';
import { RoleAutocompleteComponent } from './role/role-autocomplete/role-autocomplete.component';
import { UserListComponent } from './user/user-list/user-list.component';
import { UserDetailComponent } from './user/user-detail/user-detail.component';
import { UserLineComponent } from './user/user-line/user-line.component';
import { UserAutocompleteComponent } from './user/user-autocomplete/user-autocomplete.component';
import { UserDiaDesafioListComponent } from './userdiadesafio/userdiadesafio-list/userdiadesafio-list.component';
import { UserDiaDesafioDetailComponent } from './userdiadesafio/userdiadesafio-detail/userdiadesafio-detail.component';
import { UserDiaDesafioLineComponent } from './userdiadesafio/userdiadesafio-line/userdiadesafio-line.component';
import { UserDiaDesafioAutocompleteComponent } from './userdiadesafio/userdiadesafio-autocomplete/userdiadesafio-autocomplete.component';
import { UserDiaHabitoListComponent } from './userdiahabito/userdiahabito-list/userdiahabito-list.component';
import { UserDiaHabitoDetailComponent } from './userdiahabito/userdiahabito-detail/userdiahabito-detail.component';
import { UserDiaHabitoLineComponent } from './userdiahabito/userdiahabito-line/userdiahabito-line.component';
import { UserDiaHabitoAutocompleteComponent } from './userdiahabito/userdiahabito-autocomplete/userdiahabito-autocomplete.component';
import { UserDiaTestemunhoListComponent } from './userdiatestemunho/userdiatestemunho-list/userdiatestemunho-list.component';
import { UserDiaTestemunhoDetailComponent } from './userdiatestemunho/userdiatestemunho-detail/userdiatestemunho-detail.component';
import { UserDiaTestemunhoLineComponent } from './userdiatestemunho/userdiatestemunho-line/userdiatestemunho-line.component';
import { UserDiaTestemunhoAutocompleteComponent } from './userdiatestemunho/userdiatestemunho-autocomplete/userdiatestemunho-autocomplete.component';

@NgModule({
  imports: [
    NgbModule,
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    EntitiesRoutingModule,

    NgSelectModule,
    NgxMaskModule.forChild(),

    MatSortModule,

    CdkTableModule,

    // Primeng
    FileUploadModule,

    SharedModule
  ],
  declarations: [
    EntitiesComponent,

    DesafioListComponent,
    DesafioDetailComponent,
    DesafioLineComponent,
    DesafioAutocompleteComponent,
    HabitoListComponent,
    HabitoDetailComponent,
    HabitoLineComponent,
    HabitoAutocompleteComponent,
    RoleListComponent,
    RoleDetailComponent,
    RoleLineComponent,
    RoleAutocompleteComponent,
    UserListComponent,
    UserDetailComponent,
    UserLineComponent,
    UserAutocompleteComponent,
    UserDiaDesafioListComponent,
    UserDiaDesafioDetailComponent,
    UserDiaDesafioLineComponent,
    UserDiaDesafioAutocompleteComponent,
    UserDiaHabitoListComponent,
    UserDiaHabitoDetailComponent,
    UserDiaHabitoLineComponent,
    UserDiaHabitoAutocompleteComponent,
    UserDiaTestemunhoListComponent,
    UserDiaTestemunhoDetailComponent,
    UserDiaTestemunhoLineComponent,
    UserDiaTestemunhoAutocompleteComponent,
  ],
  exports: [
    DesafioListComponent,
    DesafioDetailComponent,
    DesafioLineComponent,
    DesafioAutocompleteComponent,
    HabitoListComponent,
    HabitoDetailComponent,
    HabitoLineComponent,
    HabitoAutocompleteComponent,
    RoleListComponent,
    RoleDetailComponent,
    RoleLineComponent,
    RoleAutocompleteComponent,
    UserListComponent,
    UserDetailComponent,
    UserLineComponent,
    UserAutocompleteComponent,
    UserDiaDesafioListComponent,
    UserDiaDesafioDetailComponent,
    UserDiaDesafioLineComponent,
    UserDiaDesafioAutocompleteComponent,
    UserDiaHabitoListComponent,
    UserDiaHabitoDetailComponent,
    UserDiaHabitoLineComponent,
    UserDiaHabitoAutocompleteComponent,
    UserDiaTestemunhoListComponent,
    UserDiaTestemunhoDetailComponent,
    UserDiaTestemunhoLineComponent,
    UserDiaTestemunhoAutocompleteComponent,
  ]
})
export class EntitiesModule {}
