//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entities.module.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import {
  MatToolbarModule,
  MatSelectModule,
  MatCheckboxModule,
  MatButtonModule,
  MatSidenavModule,
  MatIconModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatMenuModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatInputModule,
  MatProgressSpinnerModule,
  MatFormFieldModule,
  MatAutocompleteModule,
  MatTabsModule,
} from '@angular/material';
import { AutoCompleteModule } from 'primeng/autocomplete';
import { FileUploadModule } from 'primeng/fileupload';
import { PickListModule } from 'primeng/picklist';
import { TriStateCheckboxModule } from 'primeng/tristatecheckbox';
import { CalendarModule } from 'primeng/calendar';
import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';

import { SharedModule } from '../shared/shared.module';

import { EmpresaListComponent } from './empresa/empresa-list/empresa-list.component';
import { EmpresaDetailComponent } from './empresa/empresa-detail/empresa-detail.component';
import { EmpresaLineComponent } from './empresa/empresa-line/empresa-line.component';
import { EmpresaAutocompleteComponent } from './empresa/empresa-autocomplete/empresa-autocomplete.component';
import { FilialListComponent } from './filial/filial-list/filial-list.component';
import { FilialDetailComponent } from './filial/filial-detail/filial-detail.component';
import { FilialLineComponent } from './filial/filial-line/filial-line.component';
import { FilialAutocompleteComponent } from './filial/filial-autocomplete/filial-autocomplete.component';
import { UsuarioListComponent } from './usuario/usuario-list/usuario-list.component';
import { UsuarioDetailComponent } from './usuario/usuario-detail/usuario-detail.component';
import { UsuarioLineComponent } from './usuario/usuario-line/usuario-line.component';
import { UsuarioAutocompleteComponent } from './usuario/usuario-autocomplete/usuario-autocomplete.component';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,

    OwlDateTimeModule,
    OwlNativeDateTimeModule,

    // Angular Material
    MatToolbarModule,
    MatTabsModule,
    MatSelectModule,
    MatCheckboxModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatAutocompleteModule,

    // Primeng
    AutoCompleteModule,
    FileUploadModule,
    PickListModule,
    TriStateCheckboxModule,
    CalendarModule,

    SharedModule
  ],
  declarations: [
    EmpresaListComponent,
    EmpresaDetailComponent,
    EmpresaLineComponent,
    EmpresaAutocompleteComponent,    FilialListComponent,
    FilialDetailComponent,
    FilialLineComponent,
    FilialAutocompleteComponent,    UsuarioListComponent,
    UsuarioDetailComponent,
    UsuarioLineComponent,
    UsuarioAutocompleteComponent  ],
  exports: [
    EmpresaListComponent,
    EmpresaDetailComponent,
    EmpresaLineComponent,
    EmpresaAutocompleteComponent,    FilialListComponent,
    FilialDetailComponent,
    FilialLineComponent,
    FilialAutocompleteComponent,    UsuarioListComponent,
    UsuarioDetailComponent,
    UsuarioLineComponent,
    UsuarioAutocompleteComponent  ]
})
export class EntitiesModule {}
