//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entities.component.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-entities',
  template: '<router-outlet></router-outlet>'
})
export class EntitiesComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
