//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entities.module.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import {
  MatToolbarModule,
  MatSelectModule,
  MatCheckboxModule,
  MatButtonModule,
  MatSidenavModule,
  MatIconModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatMenuModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatInputModule,
  MatProgressSpinnerModule,
  MatFormFieldModule,
  MatAutocompleteModule,
  MatTabsModule,
} from '@angular/material';
import { AutoCompleteModule } from 'primeng/autocomplete';
import { FileUploadModule } from 'primeng/fileupload';
import { PickListModule } from 'primeng/picklist';
import { TriStateCheckboxModule } from 'primeng/tristatecheckbox';
import { CalendarModule } from 'primeng/calendar';
import { OwlDateTimeModule, OwlNativeDateTimeModule } from 'ng-pick-datetime';

import { SharedModule } from '../shared/shared.module';

import { AgendaListComponent } from './agenda/agenda-list/agenda-list.component';
import { AgendaDetailComponent } from './agenda/agenda-detail/agenda-detail.component';
import { AgendaLineComponent } from './agenda/agenda-line/agenda-line.component';
import { AgendaAutocompleteComponent } from './agenda/agenda-autocomplete/agenda-autocomplete.component';
import { AgendaDetalheListComponent } from './agendadetalhe/agendadetalhe-list/agendadetalhe-list.component';
import { AgendaDetalheDetailComponent } from './agendadetalhe/agendadetalhe-detail/agendadetalhe-detail.component';
import { AgendaDetalheLineComponent } from './agendadetalhe/agendadetalhe-line/agendadetalhe-line.component';
import { AgendaDetalheAutocompleteComponent } from './agendadetalhe/agendadetalhe-autocomplete/agendadetalhe-autocomplete.component';
import { AgendaPeriodoListComponent } from './agendaperiodo/agendaperiodo-list/agendaperiodo-list.component';
import { AgendaPeriodoDetailComponent } from './agendaperiodo/agendaperiodo-detail/agendaperiodo-detail.component';
import { AgendaPeriodoLineComponent } from './agendaperiodo/agendaperiodo-line/agendaperiodo-line.component';
import { AgendaPeriodoAutocompleteComponent } from './agendaperiodo/agendaperiodo-autocomplete/agendaperiodo-autocomplete.component';
import { AreaListComponent } from './area/area-list/area-list.component';
import { AreaDetailComponent } from './area/area-detail/area-detail.component';
import { AreaLineComponent } from './area/area-line/area-line.component';
import { AreaAutocompleteComponent } from './area/area-autocomplete/area-autocomplete.component';
import { BloqueioListComponent } from './bloqueio/bloqueio-list/bloqueio-list.component';
import { BloqueioDetailComponent } from './bloqueio/bloqueio-detail/bloqueio-detail.component';
import { BloqueioLineComponent } from './bloqueio/bloqueio-line/bloqueio-line.component';
import { BloqueioAutocompleteComponent } from './bloqueio/bloqueio-autocomplete/bloqueio-autocomplete.component';
import { ConsultaListComponent } from './consulta/consulta-list/consulta-list.component';
import { ConsultaDetailComponent } from './consulta/consulta-detail/consulta-detail.component';
import { ConsultaLineComponent } from './consulta/consulta-line/consulta-line.component';
import { ConsultaAutocompleteComponent } from './consulta/consulta-autocomplete/consulta-autocomplete.component';
import { EspecialidadeListComponent } from './especialidade/especialidade-list/especialidade-list.component';
import { EspecialidadeDetailComponent } from './especialidade/especialidade-detail/especialidade-detail.component';
import { EspecialidadeLineComponent } from './especialidade/especialidade-line/especialidade-line.component';
import { EspecialidadeAutocompleteComponent } from './especialidade/especialidade-autocomplete/especialidade-autocomplete.component';
import { PacienteListComponent } from './paciente/paciente-list/paciente-list.component';
import { PacienteDetailComponent } from './paciente/paciente-detail/paciente-detail.component';
import { PacienteLineComponent } from './paciente/paciente-line/paciente-line.component';
import { PacienteAutocompleteComponent } from './paciente/paciente-autocomplete/paciente-autocomplete.component';
import { ParametroListComponent } from './parametro/parametro-list/parametro-list.component';
import { ParametroDetailComponent } from './parametro/parametro-detail/parametro-detail.component';
import { ParametroLineComponent } from './parametro/parametro-line/parametro-line.component';
import { ParametroAutocompleteComponent } from './parametro/parametro-autocomplete/parametro-autocomplete.component';
import { ProfissionalSaudeListComponent } from './profissionalsaude/profissionalsaude-list/profissionalsaude-list.component';
import { ProfissionalSaudeDetailComponent } from './profissionalsaude/profissionalsaude-detail/profissionalsaude-detail.component';
import { ProfissionalSaudeLineComponent } from './profissionalsaude/profissionalsaude-line/profissionalsaude-line.component';
import { ProfissionalSaudeAutocompleteComponent } from './profissionalsaude/profissionalsaude-autocomplete/profissionalsaude-autocomplete.component';
import { QualificacaoProfissionalListComponent } from './qualificacaoprofissional/qualificacaoprofissional-list/qualificacaoprofissional-list.component';
import { QualificacaoProfissionalDetailComponent } from './qualificacaoprofissional/qualificacaoprofissional-detail/qualificacaoprofissional-detail.component';
import { QualificacaoProfissionalLineComponent } from './qualificacaoprofissional/qualificacaoprofissional-line/qualificacaoprofissional-line.component';
import { QualificacaoProfissionalAutocompleteComponent } from './qualificacaoprofissional/qualificacaoprofissional-autocomplete/qualificacaoprofissional-autocomplete.component';
import { StatusListComponent } from './status/status-list/status-list.component';
import { StatusDetailComponent } from './status/status-detail/status-detail.component';
import { StatusLineComponent } from './status/status-line/status-line.component';
import { StatusAutocompleteComponent } from './status/status-autocomplete/status-autocomplete.component';
import { TipoAgendaListComponent } from './tipoagenda/tipoagenda-list/tipoagenda-list.component';
import { TipoAgendaDetailComponent } from './tipoagenda/tipoagenda-detail/tipoagenda-detail.component';
import { TipoAgendaLineComponent } from './tipoagenda/tipoagenda-line/tipoagenda-line.component';
import { TipoAgendaAutocompleteComponent } from './tipoagenda/tipoagenda-autocomplete/tipoagenda-autocomplete.component';
import { TipoConsultaListComponent } from './tipoconsulta/tipoconsulta-list/tipoconsulta-list.component';
import { TipoConsultaDetailComponent } from './tipoconsulta/tipoconsulta-detail/tipoconsulta-detail.component';
import { TipoConsultaLineComponent } from './tipoconsulta/tipoconsulta-line/tipoconsulta-line.component';
import { TipoConsultaAutocompleteComponent } from './tipoconsulta/tipoconsulta-autocomplete/tipoconsulta-autocomplete.component';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,

    OwlDateTimeModule,
    OwlNativeDateTimeModule,

    // Angular Material
    MatToolbarModule,
    MatTabsModule,
    MatSelectModule,
    MatCheckboxModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatAutocompleteModule,

    // Primeng
    AutoCompleteModule,
    FileUploadModule,
    PickListModule,
    TriStateCheckboxModule,
    CalendarModule,

    SharedModule
  ],
  declarations: [
    AgendaListComponent,
    AgendaDetailComponent,
    AgendaLineComponent,
    AgendaAutocompleteComponent,    AgendaDetalheListComponent,
    AgendaDetalheDetailComponent,
    AgendaDetalheLineComponent,
    AgendaDetalheAutocompleteComponent,    AgendaPeriodoListComponent,
    AgendaPeriodoDetailComponent,
    AgendaPeriodoLineComponent,
    AgendaPeriodoAutocompleteComponent,    AreaListComponent,
    AreaDetailComponent,
    AreaLineComponent,
    AreaAutocompleteComponent,    BloqueioListComponent,
    BloqueioDetailComponent,
    BloqueioLineComponent,
    BloqueioAutocompleteComponent,    ConsultaListComponent,
    ConsultaDetailComponent,
    ConsultaLineComponent,
    ConsultaAutocompleteComponent,    EspecialidadeListComponent,
    EspecialidadeDetailComponent,
    EspecialidadeLineComponent,
    EspecialidadeAutocompleteComponent,    PacienteListComponent,
    PacienteDetailComponent,
    PacienteLineComponent,
    PacienteAutocompleteComponent,    ParametroListComponent,
    ParametroDetailComponent,
    ParametroLineComponent,
    ParametroAutocompleteComponent,    ProfissionalSaudeListComponent,
    ProfissionalSaudeDetailComponent,
    ProfissionalSaudeLineComponent,
    ProfissionalSaudeAutocompleteComponent,    QualificacaoProfissionalListComponent,
    QualificacaoProfissionalDetailComponent,
    QualificacaoProfissionalLineComponent,
    QualificacaoProfissionalAutocompleteComponent,    StatusListComponent,
    StatusDetailComponent,
    StatusLineComponent,
    StatusAutocompleteComponent,    TipoAgendaListComponent,
    TipoAgendaDetailComponent,
    TipoAgendaLineComponent,
    TipoAgendaAutocompleteComponent,    TipoConsultaListComponent,
    TipoConsultaDetailComponent,
    TipoConsultaLineComponent,
    TipoConsultaAutocompleteComponent  ],
  exports: [
    AgendaListComponent,
    AgendaDetailComponent,
    AgendaLineComponent,
    AgendaAutocompleteComponent,    AgendaDetalheListComponent,
    AgendaDetalheDetailComponent,
    AgendaDetalheLineComponent,
    AgendaDetalheAutocompleteComponent,    AgendaPeriodoListComponent,
    AgendaPeriodoDetailComponent,
    AgendaPeriodoLineComponent,
    AgendaPeriodoAutocompleteComponent,    AreaListComponent,
    AreaDetailComponent,
    AreaLineComponent,
    AreaAutocompleteComponent,    BloqueioListComponent,
    BloqueioDetailComponent,
    BloqueioLineComponent,
    BloqueioAutocompleteComponent,    ConsultaListComponent,
    ConsultaDetailComponent,
    ConsultaLineComponent,
    ConsultaAutocompleteComponent,    EspecialidadeListComponent,
    EspecialidadeDetailComponent,
    EspecialidadeLineComponent,
    EspecialidadeAutocompleteComponent,    PacienteListComponent,
    PacienteDetailComponent,
    PacienteLineComponent,
    PacienteAutocompleteComponent,    ParametroListComponent,
    ParametroDetailComponent,
    ParametroLineComponent,
    ParametroAutocompleteComponent,    ProfissionalSaudeListComponent,
    ProfissionalSaudeDetailComponent,
    ProfissionalSaudeLineComponent,
    ProfissionalSaudeAutocompleteComponent,    QualificacaoProfissionalListComponent,
    QualificacaoProfissionalDetailComponent,
    QualificacaoProfissionalLineComponent,
    QualificacaoProfissionalAutocompleteComponent,    StatusListComponent,
    StatusDetailComponent,
    StatusLineComponent,
    StatusAutocompleteComponent,    TipoAgendaListComponent,
    TipoAgendaDetailComponent,
    TipoAgendaLineComponent,
    TipoAgendaAutocompleteComponent,    TipoConsultaListComponent,
    TipoConsultaDetailComponent,
    TipoConsultaLineComponent,
    TipoConsultaAutocompleteComponent  ]
})
export class EntitiesModule {}
