//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/enumerators.service.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { MessageService } from '../util/message.service';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';

@Injectable()
export class EnumeratorsService {

    protected apiUrl: string = environment.baseUrl + '/v1/enums/';

    constructor(protected http: HttpClient, protected messageService: MessageService) {
    }

    /**
     * Retorna uma coleção de valores do enumerator informado.
     * @param enumType
     */
    public getEnumValues(enumType: string): Observable<any[]> {
        return this.http.get<any[]>(this.apiUrl + enumType);
    }

    /**
     * Retorna a coleção de valores do enumerator: Genero
     */
    public getGeneroValues(): Observable<any[]> {
        return this.getEnumValues('Genero');
    }

    /**
     * Retorna a coleção de valores do enumerator: Ocorrencia
     */
    public getOcorrenciaValues(): Observable<any[]> {
        return this.getEnumValues('Ocorrencia');
    }

    /**
     * Retorna a coleção de valores do enumerator: SimNao
     */
    public getSimNaoValues(): Observable<any[]> {
        return this.getEnumValues('SimNao');
    }

    /**
     * Retorna a coleção de valores do enumerator: Status
     */
    public getStatusValues(): Observable<any[]> {
        return this.getEnumValues('Status');
    }

}
