ALTER TABLE habito DROP COLUMN dia_mes;
ALTER TABLE desafio DROP COLUMN dia_mes;

ALTER TABLE desafio ADD COLUMN dia_8 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_9 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_10 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_11 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_12 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_13 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_14 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_15 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_16 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_17 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_18 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_19 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_20 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_21 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_22 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_23 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_24 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_25 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_26 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_27 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_28 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_29 int not null default 0;
ALTER TABLE desafio ADD COLUMN dia_30 int not null default 0;

ALTER TABLE habito ADD COLUMN dia_8 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_9 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_10 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_11 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_12 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_13 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_14 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_15 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_16 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_17 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_18 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_19 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_20 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_21 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_22 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_23 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_24 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_25 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_26 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_27 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_28 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_29 int not null default 0;
ALTER TABLE habito ADD COLUMN dia_30 int not null default 0;

