/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/manager/Manager.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.manager;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.jus.framework.piloto.core.manager.AppBaseManagerImpl;
import br.jus.framework.piloto.dao.FilialDao;
import br.jus.framework.piloto.domain.Filial;

import java.util.Map;

import javax.validation.ConstraintViolationException;

import org.apache.commons.lang3.StringUtils;

import br.jus.framework.model.exception.ModelException;
import br.jus.framework.search.impl.Operator;

/**
 * Implementação Manager da entidade: {@link Filial} 
 *
 * @see AppBaseManagerImpl
 */
@Stateless
public class FilialManager extends AppBaseManagerImpl<Long, Filial, FilialDao> {

    public FilialManager() {
        super(Filial.class);
    }

    @Override
    @EJB
    protected void setSearch(FilialDao search) {
        super.setSearch(search);
    }

    @Override
    public void validateEntityFields(Filial entity, boolean isInsert) throws ConstraintViolationException, ModelException {
        super.validateEntityFields(entity, isInsert);

        Map<String, Object[]> messagesMap = ModelException.createMessagesMap();

        if (!messagesMap.isEmpty()) {
            throw new ModelException(messagesMap);
        }
    }
}