/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/manager/Manager.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.manager;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.jus.framework.piloto.core.manager.AppBaseManagerImpl;
import br.jus.framework.piloto.dao.UsuarioDao;
import br.jus.framework.piloto.domain.Usuario;

import java.util.Map;

import javax.validation.ConstraintViolationException;

import org.apache.commons.lang3.StringUtils;

import br.jus.framework.model.exception.ModelException;
import br.jus.framework.search.impl.Operator;

/**
 * Implementação Manager da entidade: {@link Usuario} 
 *
 * @see AppBaseManagerImpl
 */
@Stateless
public class UsuarioManager extends AppBaseManagerImpl<Long, Usuario, UsuarioDao> {

    public UsuarioManager() {
        super(Usuario.class);
    }

    @Override
    @EJB
    protected void setSearch(UsuarioDao search) {
        super.setSearch(search);
    }

    @Override
    public void validateEntityFields(Usuario entity, boolean isInsert) throws ConstraintViolationException, ModelException {
        super.validateEntityFields(entity, isInsert);

        Map<String, Object[]> messagesMap = ModelException.createMessagesMap();

        if (!messagesMap.isEmpty()) {
            throw new ModelException(messagesMap);
        }
    }
}