//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//

import { BaseEntityAudited } from '../../framework/entity/baseEntityAudited';

export class Usuario extends BaseEntityAudited {
    // Raw attributes
    nome: string;
    login: string;
    password: string;
    email: string;
    fotoBinary;
    fotoFileName: string;
    fotoContentType: string;
    fotoSize: number;

    constructor(json?: any, depth?: number) {
        super(json, depth);
    }

    /**
     * Converter um array de json em um array de objetos.
     */
    static toArray(jsons: any[], depth?: number): Usuario[] {
        const entities: Usuario[] = [];
        if (jsons != null) {
            for (const json of jsons) {
                entities.push(new Usuario(json, depth));
            }
        }
        return entities;
    }

    /**
     * Responsavel por carregar os campos
     */
    protected loadEntityFields(json?: any, depth?: number): void {
        super.loadEntityFields(json);
        this.nome = json.nome;
        this.login = json.login;
        this.password = json.password;
        this.email = json.email;
        this.fotoFileName = json.fotoFileName;
        this.fotoContentType = json.fotoContentType;
        this.fotoSize = json.fotoSize;
        if (depth && depth-- > 0) {
        }
    }
}
