//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity.datasource.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Usuario } from './usuario';
import { UsuarioService } from './usuario.service';
import { EntityDataSource } from '../../framework/service/entity.datasource';
import { MatPaginator, MatSort } from '@angular/material';

/**
 * Implementação da classe de serviço da entidade Usuario.
 */
export class UsuarioDataSource extends EntityDataSource<Usuario, UsuarioService> {

  constructor(public paginator: MatPaginator, public sort: MatSort, public entityService: UsuarioService) {
    super(paginator, sort, entityService);
  }

}
