//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-autocomplete/entity-auto-complete.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, OnInit, forwardRef } from '@angular/core';
import { EntityCompleteComponent } from '../../../framework/components/entity-auto-complete.component';
import { MessageService } from '../../../util/message.service';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { Empresa } from '../empresa';
import { EmpresaService } from '../empresa.service';

export const EMPRESA_AUTO_COMPLETE_CONTROL_VALUE_ACCESSOR: any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => EmpresaAutocompleteComponent),
  multi: true
};

@Component({
  selector: 'app-empresa-autocomplete',
  templateUrl: './empresa-autocomplete.component.html',
  styleUrls: ['./empresa-autocomplete.component.scss'],
  providers: [EMPRESA_AUTO_COMPLETE_CONTROL_VALUE_ACCESSOR]
})
export class EmpresaAutocompleteComponent extends EntityCompleteComponent<Empresa, EmpresaService> {

  constructor(protected entityService: EmpresaService, protected messageService: MessageService) {
    super(entityService, messageService);
  }

}

