/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/service/resource/Resource.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.service.resource;

import java.time.LocalDateTime;

import br.jus.framework.piloto.domain.Empresa;
import br.jus.framework.service.impl.BaseEntityResourceImpl;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Resource da entidade Empresa.
 */
@XmlRootElement
public class EmpresaResource extends BaseEntityResourceImpl<Long, Empresa> {

    private static final long serialVersionUID = 1L;

    private Long versaoEntidade;
    private LocalDateTime dhCriacao;
    private LocalDateTime dhModificacao;
    private Integer flHabilitado;
    private String nmLogin;
    private String codigo;
    private String nomeFantasia;
    private String razaoSocial;
    private String nmLoginAlteracao;

    public EmpresaResource() {
        super();
    }

    public EmpresaResource(Empresa entity) {
        super(entity);
        if (entity != null) {

            setVersaoEntidade(entity.getVersaoEntidade());
            setDhCriacao(entity.getDhCriacao());
            setDhModificacao(entity.getDhModificacao());
            setFlHabilitado(entity.getFlHabilitado());
            setNmLogin(entity.getNmLogin());
            setCodigo(entity.getCodigo());
            setNomeFantasia(entity.getNomeFantasia());
            setRazaoSocial(entity.getRazaoSocial());
            setNmLoginAlteracao(entity.getNmLoginAlteracao());
        }
    }

    // -- [versaoEntidade] ------------------------
    public Long getVersaoEntidade() {
        return versaoEntidade;
    }

    public void setVersaoEntidade(Long versaoEntidade) {
        this.versaoEntidade = versaoEntidade;
    }

    // -- [dhCriacao] ------------------------
    public LocalDateTime getDhCriacao() {
        return dhCriacao;
    }

    public void setDhCriacao(LocalDateTime dhCriacao) {
        this.dhCriacao = dhCriacao;
    }

    // -- [dhModificacao] ------------------------
    public LocalDateTime getDhModificacao() {
        return dhModificacao;
    }

    public void setDhModificacao(LocalDateTime dhModificacao) {
        this.dhModificacao = dhModificacao;
    }

    // -- [flHabilitado] ------------------------
    public Integer getFlHabilitado() {
        return flHabilitado;
    }

    public void setFlHabilitado(Integer flHabilitado) {
        this.flHabilitado = flHabilitado;
    }

    // -- [nmLogin] ------------------------
    public String getNmLogin() {
        return nmLogin;
    }

    public void setNmLogin(String nmLogin) {
        this.nmLogin = nmLogin;
    }

    // -- [codigo] ------------------------
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    // -- [nomeFantasia] ------------------------
    public String getNomeFantasia() {
        return nomeFantasia;
    }

    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    // -- [razaoSocial] ------------------------
    public String getRazaoSocial() {
        return razaoSocial;
    }

    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

    // -- [nmLoginAlteracao] ------------------------
    public String getNmLoginAlteracao() {
        return nmLoginAlteracao;
    }

    public void setNmLoginAlteracao(String nmLoginAlteracao) {
        this.nmLoginAlteracao = nmLoginAlteracao;
    }

}