/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/service/resource/Resource.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.service.resource;

import br.jus.framework.piloto.domain.Usuario;
import br.jus.framework.service.impl.BaseEntityAuditedResourceImpl;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Resource da entidade Usuario.
 */
@XmlRootElement
public class UsuarioResource extends BaseEntityAuditedResourceImpl<Long, Usuario> {

    private static final long serialVersionUID = 1L;

    private String nome;
    private String login;
    private String password;
    private String email;
    private byte[] fotoBinary;
    private String fotoFileName;
    private String fotoContentType;
    private Long fotoSize;

    public UsuarioResource() {
        super();
    }

    public UsuarioResource(Usuario entity) {
        super(entity);
        if (entity != null) {

            setNome(entity.getNome());
            setLogin(entity.getLogin());
            setPassword(entity.getPassword());
            setEmail(entity.getEmail());
            setFotoBinary(entity.getFotoBinary());
            setFotoFileName(entity.getFotoFileName());
            setFotoContentType(entity.getFotoContentType());
            setFotoSize(entity.getFotoSize());
        }
    }

    // -- [nome] ------------------------
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    // -- [login] ------------------------
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    // -- [password] ------------------------
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // -- [email] ------------------------
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    // -- [fotoBinary] ------------------------
    public byte[] getFotoBinary() {
        return fotoBinary;
    }

    public void setFotoBinary(byte[] fotoBinary) {
        this.fotoBinary = fotoBinary;
    }

    // -- [fotoFileName] ------------------------
    public String getFotoFileName() {
        return fotoFileName;
    }

    public void setFotoFileName(String fotoFileName) {
        this.fotoFileName = fotoFileName;
    }

    // -- [fotoContentType] ------------------------
    public String getFotoContentType() {
        return fotoContentType;
    }

    public void setFotoContentType(String fotoContentType) {
        this.fotoContentType = fotoContentType;
    }

    // -- [fotoSize] ------------------------
    public Long getFotoSize() {
        return fotoSize;
    }

    public void setFotoSize(Long fotoSize) {
        this.fotoSize = fotoSize;
    }

}