//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-list/entity-list.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, Input } from '@angular/core';
import { EntityListComponent } from '../../../framework/components/entity-list.component';
import { Router } from '@angular/router';
import { MessageService } from '../../../util/message.service';
import { MatDialog } from '@angular/material';
import { FilterMetadata } from '../../../framework/service/paging/filtermetadata';
import { Operator } from '../../../framework/service/paging/operator';
import { Empresa } from '../empresa';
import { EmpresaService } from '../empresa.service';
import { EmpresaDataSource } from '../empresa.datasource';

@Component({
  selector: 'app-empresa-list',
  templateUrl: './empresa-list.component.html',
  styleUrls: ['./empresa-list.component.scss']
})
export class EmpresaListComponent extends EntityListComponent<Empresa, EmpresaService> {


    constructor(protected router: Router,
        protected messageService: MessageService,
        protected confirmDeleteDialog: MatDialog,
        protected entityService: EmpresaService) {
        super(router, messageService, confirmDeleteDialog, entityService, 'Empresa');
        // inicialização do dataSource
        this.dataSource = new EmpresaDataSource(this.paginator, this.sort, this.entityService);
        // configura as colunas exibidas no datatable.
        this.displayedColumns = [
            'versaoEntidade',
            'dhCriacao',
            'dhModificacao',
            'flHabilitado',
            'nmLogin',
            'codigo',
            'actions'
        ];
        // configura os campos de filtro
        this.filters['versaoEntidade'] = new FilterMetadata(null, Operator.EQ);
        this.filters['dhCriacao'] = new FilterMetadata(null, Operator.EQ);
        this.filters['dhModificacao'] = new FilterMetadata(null, Operator.EQ);
        this.filters['flHabilitado'] = new FilterMetadata(null, Operator.EQ);
        this.filters['nmLogin'] = new FilterMetadata(null, Operator.LI);
        this.filters['codigo'] = new FilterMetadata(null, Operator.LI);
        this.filters['nomeFantasia'] = new FilterMetadata(null, Operator.LI);
        this.filters['razaoSocial'] = new FilterMetadata(null, Operator.LI);
        this.filters['nmLoginAlteracao'] = new FilterMetadata(null, Operator.LI);
    }

}
