/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/domain/Entity.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import br.jus.framework.piloto.core.domain.BaseEntityImpl;

import com.google.common.base.MoreObjects;

@Entity
@Table(schema = "cadastros", name = "empresa")

/**
 * Implementação da entidade de domínio: Empresa
 *
 */
public class Empresa extends BaseEntityImpl<Long> {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Empresa.class);

    // Raw attributes
    private Long versaoEntidade;
    private LocalDateTime dhCriacao;
    private LocalDateTime dhModificacao;
    private Integer flHabilitado;
    private String nmLogin;
    private String codigo;
    private String nomeFantasia;
    private String razaoSocial;
    private String nmLoginAlteracao;

    @Override
    public String entityClassName() {
        return Empresa.class.getSimpleName();
    }

    // -----------------------
    // Simple Primary Key
    // -----------------------

    /**
     * Returns the simple primary key.
     */
    @Column(name = "id_empresa", precision = 19)
    @GeneratedValue(strategy = SEQUENCE, generator = "*")
    @Id
    @SequenceGenerator(name = "*", sequenceName = "*", schema = "cadastros", allocationSize = 1)
    public Long getId() {
        return super.getId();
    }

    /**
     * Set the composite primary key.
     * @param id the composite primary key.
     */
    @Override
    public void setId(Long id) {
        super.setId(id);
    }

    public Empresa id(Long id) {
        setId(id);
        return this;
    }

    // -- [versaoEntidade] ------------------------
    @Digits(integer = 19, fraction = 0)
    @NotNull
    @Column(name = "versao_entidade", nullable = false, precision = 19)
    public Long getVersaoEntidade() {
        return versaoEntidade;
    }

    public void setVersaoEntidade(Long versaoEntidade) {
        this.versaoEntidade = versaoEntidade;
    }

    public Empresa versaoEntidade(Long versaoEntidade) {
        setVersaoEntidade(versaoEntidade);
        return this;
    }

    // -- [dhCriacao] ------------------------
    @NotNull
    @Column(name = "dh_criacao", nullable = false, length = 29)
    public LocalDateTime getDhCriacao() {
        return dhCriacao;
    }

    public void setDhCriacao(LocalDateTime dhCriacao) {
        this.dhCriacao = dhCriacao;
    }

    public Empresa dhCriacao(LocalDateTime dhCriacao) {
        setDhCriacao(dhCriacao);
        return this;
    }

    // -- [dhModificacao] ------------------------
    @NotNull
    @Column(name = "dh_modificacao", nullable = false, length = 29)
    public LocalDateTime getDhModificacao() {
        return dhModificacao;
    }

    public void setDhModificacao(LocalDateTime dhModificacao) {
        this.dhModificacao = dhModificacao;
    }

    public Empresa dhModificacao(LocalDateTime dhModificacao) {
        setDhModificacao(dhModificacao);
        return this;
    }

    // -- [flHabilitado] ------------------------
    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "fl_habilitado", nullable = false, precision = 10)
    public Integer getFlHabilitado() {
        return flHabilitado;
    }

    public void setFlHabilitado(Integer flHabilitado) {
        this.flHabilitado = flHabilitado;
    }

    public Empresa flHabilitado(Integer flHabilitado) {
        setFlHabilitado(flHabilitado);
        return this;
    }

    // -- [nmLogin] ------------------------
    @Size(max = 255)
    @Column(name = "nm_login")
    public String getNmLogin() {
        return nmLogin;
    }

    public void setNmLogin(String nmLogin) {
        this.nmLogin = nmLogin;
    }

    public Empresa nmLogin(String nmLogin) {
        setNmLogin(nmLogin);
        return this;
    }

    // -- [codigo] ------------------------
    @NotEmpty
    @Size(max = 255)
    @Column(name = "codigo", nullable = false)
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Empresa codigo(String codigo) {
        setCodigo(codigo);
        return this;
    }

    // -- [nomeFantasia] ------------------------
    @NotEmpty
    @Size(max = 255)
    @Column(name = "nome_fantasia", nullable = false)
    public String getNomeFantasia() {
        return nomeFantasia;
    }

    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    public Empresa nomeFantasia(String nomeFantasia) {
        setNomeFantasia(nomeFantasia);
        return this;
    }

    // -- [razaoSocial] ------------------------
    @NotEmpty
    @Size(max = 255)
    @Column(name = "razao_social", nullable = false)
    public String getRazaoSocial() {
        return razaoSocial;
    }

    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

    public Empresa razaoSocial(String razaoSocial) {
        setRazaoSocial(razaoSocial);
        return this;
    }

    // -- [nmLoginAlteracao] ------------------------
    @Size(max = 255)
    @Column(name = "nm_login_alteracao")
    public String getNmLoginAlteracao() {
        return nmLoginAlteracao;
    }

    public void setNmLoginAlteracao(String nmLoginAlteracao) {
        this.nmLoginAlteracao = nmLoginAlteracao;
    }

    public Empresa nmLoginAlteracao(String nmLoginAlteracao) {
        setNmLoginAlteracao(nmLoginAlteracao);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Empresa withDefaults() {
        return this;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("versaoEntidade", getVersaoEntidade()) //
                .add("dhCriacao", getDhCriacao()) //
                .add("dhModificacao", getDhModificacao()) //
                .add("flHabilitado", getFlHabilitado()) //
                .add("nmLogin", getNmLogin()) //
                .add("codigo", getCodigo()) //
                .add("nomeFantasia", getNomeFantasia()) //
                .add("razaoSocial", getRazaoSocial()) //
                .add("nmLoginAlteracao", getNmLoginAlteracao()) //
                .toString();
    }
}