//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-detail/entity-detail.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, Input } from '@angular/core';
import { EntityDetailComponent } from '../../../framework/components/entity-detail.component';
import { ActivatedRoute, Router } from '@angular/router';
import { Location } from '@angular/common';
import { MessageService } from '../../../util/message.service';
import { EnumeratorsService } from '../../enumerators.service';

import { Empresa } from '../empresa';
import { EmpresaService } from '../empresa.service';

@Component({
  selector: 'app-empresa-detail',
  templateUrl: './empresa-detail.component.html',
  styleUrls: ['./empresa-detail.component.scss']
})
export class EmpresaDetailComponent extends EntityDetailComponent<Empresa, EmpresaService> {




    constructor(protected route: ActivatedRoute, protected router: Router, protected messageService: MessageService,
        protected location: Location,
        protected enumeratorsService: EnumeratorsService,
        protected entityService: EmpresaService) {
        super(route, router, messageService, location, enumeratorsService, entityService, 'Empresa');
    }

    protected loadEnumValues(): void {
    }

    protected loadEntityRelations(): void {
    }



}


