//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-autocomplete/entity-auto-complete.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, OnInit, forwardRef } from '@angular/core';
import { EntityCompleteComponent } from '../../../framework/components/entity-auto-complete.component';
import { MessageService } from '../../../util/message.service';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { Usuario } from '../usuario';
import { UsuarioService } from '../usuario.service';

export const USUARIO_AUTO_COMPLETE_CONTROL_VALUE_ACCESSOR: any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => UsuarioAutocompleteComponent),
  multi: true
};

@Component({
  selector: 'app-usuario-autocomplete',
  templateUrl: './usuario-autocomplete.component.html',
  styleUrls: ['./usuario-autocomplete.component.scss'],
  providers: [USUARIO_AUTO_COMPLETE_CONTROL_VALUE_ACCESSOR]
})
export class UsuarioAutocompleteComponent extends EntityCompleteComponent<Usuario, UsuarioService> {

  constructor(protected entityService: UsuarioService, protected messageService: MessageService) {
    super(entityService, messageService);
  }

}

