//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-autocomplete/entity-autocomplete.component.spec.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { UsuarioAutocompleteComponent } from './usuario-autocomplete.component';

describe('UsuarioAutocompleteComponent', () => {
  let component: UsuarioAutocompleteComponent;
  let fixture: ComponentFixture<UsuarioAutocompleteComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ UsuarioAutocompleteComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(UsuarioAutocompleteComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
