export enum SituacaoAcesso {
    ACESSO_LIBERADO = 'ACESSO_LIBERADO',
    ACESSO_NEGADO = 'ACESSO_NEGADO',
    LICENCA_SEM_VENCIMENTO = 'LICENCA_SEM_VENCIMENTO',
    CEDIDO = 'CEDIDO',
    DEMITIDO_EXONERADO_OU_DEVOLVIDO = 'DEMITIDO_EXONERADO_OU_DEVOLVIDO',
}
