//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entities.module.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { NgModule } from '@angular/core';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { MatSortModule } from '@angular/material';
import { CdkTableModule } from '@angular/cdk/table';
import { FileUploadModule } from 'primeng/fileupload';

import { NgSelectModule } from '@ng-select/ng-select';
import { NgxMaskModule } from 'ngx-mask';

import { SharedModule } from '../shared/shared.module';
import { EntitiesRoutingModule } from './entities-routing.module';
import { EntitiesComponent } from './entities.component';

import { ParametroListComponent } from './parametro/parametro-list/parametro-list.component';
import { ParametroDetailComponent } from './parametro/parametro-detail/parametro-detail.component';
import { ParametroLineComponent } from './parametro/parametro-line/parametro-line.component';
import { ParametroAutocompleteComponent } from './parametro/parametro-autocomplete/parametro-autocomplete.component';


@NgModule({
  imports: [
    NgbModule,
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    EntitiesRoutingModule,

    NgSelectModule,
    NgxMaskModule.forChild(),

    MatSortModule,

    CdkTableModule,

    // Primeng
    FileUploadModule,

    SharedModule
  ],
  declarations: [
    EntitiesComponent,

    
    ParametroListComponent,
    ParametroDetailComponent,
    ParametroLineComponent,
    ParametroAutocompleteComponent,
    
  ],
  exports: [
    ParametroListComponent,
    ParametroDetailComponent,
    ParametroLineComponent,
    ParametroAutocompleteComponent
  ]
})
export class EntitiesModule {}
