//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/app.module.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, APP_INITIALIZER } from '@angular/core';

import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HomeComponent } from './home/home.component';
import { LayoutModule } from '@angular/cdk/layout';
import {
  MatToolbarModule,
  MatCheckboxModule,
  MatButtonModule,
  MatSidenavModule,
  MatIconModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatMenuModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatInputModule,
  MatProgressSpinnerModule,
  MatFormFieldModule,
  MatDialogModule
} from '@angular/material';
import { OwlDateTimeModule, OwlNativeDateTimeModule, OWL_DATE_TIME_LOCALE } from 'ng-pick-datetime';
import { DashboardComponent } from './dashboard/dashboard.component';
import { MessageService } from './util/message.service';
import { EnumeratorsService } from './entities/enumerators.service';
import { ToastrModule } from 'ngx-toastr';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { AppRoutingModule } from './app-routing.module';
import { SharedModule } from './shared/shared.module';
import { ConfirmDeleteDialogComponent } from './shared/confirm-delete-dialog/confirm-delete-dialog.component';
import { initializer } from './keycloak/app.init';
import { KeycloakService } from 'keycloak-angular';
import { RequestInterceptor } from './util/interceptor/request.interceptor';
import { SpinnerService } from './util/spinner/spinner.service';
import { SpinnerComponent } from './util/spinner/spinner.component';

import { DesafioModule } from './entities/desafio/desafio.module';
import { DesafioService } from './entities/desafio/desafio.service';
import { HabitoModule } from './entities/habito/habito.module';
import { HabitoService } from './entities/habito/habito.service';
import { RoleModule } from './entities/role/role.module';
import { RoleService } from './entities/role/role.service';
import { UserModule } from './entities/user/user.module';
import { UserService } from './entities/user/user.service';
import { UserDiaDesafioModule } from './entities/userdiadesafio/userdiadesafio.module';
import { UserDiaDesafioService } from './entities/userdiadesafio/userdiadesafio.service';
import { UserDiaHabitoModule } from './entities/userdiahabito/userdiahabito.module';
import { UserDiaHabitoService } from './entities/userdiahabito/userdiahabito.service';
import { UserDiaTestemunhoModule } from './entities/userdiatestemunho/userdiatestemunho.module';
import { UserDiaTestemunhoService } from './entities/userdiatestemunho/userdiatestemunho.service';

@NgModule({
  declarations: [
    AppComponent,
    SpinnerComponent,
    HomeComponent,
    DashboardComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    ToastrModule.forRoot({closeButton: true, progressBar: true}),
    HttpClientModule,
    LayoutModule,
    FormsModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatDialogModule,

    DesafioModule,
    HabitoModule,
    RoleModule,
    UserModule,
    UserDiaDesafioModule,
    UserDiaHabitoModule,
    UserDiaTestemunhoModule,
    
    SharedModule
  ],
  providers: [
    DesafioService,
    HabitoService,
    RoleService,
    UserService,
    UserDiaDesafioService,
    UserDiaHabitoService,
    UserDiaTestemunhoService,
	EnumeratorsService,
	MessageService,
    KeycloakService,
    SpinnerService,
    {provide: OWL_DATE_TIME_LOCALE, useValue: 'pt'},
    {
      provide: APP_INITIALIZER,
      useFactory: initializer,
      multi: true,
      deps: [KeycloakService]
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: RequestInterceptor,
      multi: true
    }
  ],
  entryComponents: [
    ConfirmDeleteDialogComponent
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }


