//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/app.module.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, APP_INITIALIZER } from '@angular/core';

import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HomeComponent } from './home/home.component';
import { LayoutModule } from '@angular/cdk/layout';
import {
  MatToolbarModule,
  MatCheckboxModule,
  MatButtonModule,
  MatSidenavModule,
  MatIconModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatMenuModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatInputModule,
  MatProgressSpinnerModule,
  MatFormFieldModule,
  MatDialogModule
} from '@angular/material';
import { OwlDateTimeModule, OwlNativeDateTimeModule, OWL_DATE_TIME_LOCALE } from 'ng-pick-datetime';
import { DashboardComponent } from './dashboard/dashboard.component';
import { MessageService } from './util/message.service';
import { EnumeratorsService } from './entities/enumerators.service';
import { ToastrModule } from 'ngx-toastr';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { AppRoutingModule } from './app-routing.module';
import { SharedModule } from './shared/shared.module';
import { ConfirmDeleteDialogComponent } from './shared/confirm-delete-dialog/confirm-delete-dialog.component';
import { initializer } from './keycloak/app.init';
import { KeycloakService } from 'keycloak-angular';
import { RequestInterceptor } from './util/interceptor/request.interceptor';
import { SpinnerService } from './util/spinner/spinner.service';
import { SpinnerComponent } from './util/spinner/spinner.component';

import { EmpresaModule } from './entities/empresa/empresa.module';
import { EmpresaService } from './entities/empresa/empresa.service';
import { FilialModule } from './entities/filial/filial.module';
import { FilialService } from './entities/filial/filial.service';
import { UsuarioModule } from './entities/usuario/usuario.module';
import { UsuarioService } from './entities/usuario/usuario.service';

@NgModule({
  declarations: [
    AppComponent,
    SpinnerComponent,
    HomeComponent,
    DashboardComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    ToastrModule.forRoot({closeButton: true, progressBar: true}),
    HttpClientModule,
    LayoutModule,
    FormsModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatDialogModule,

    EmpresaModule,
    FilialModule,
    UsuarioModule,
    
    SharedModule
  ],
  providers: [
    EmpresaService,
    FilialService,
    UsuarioService,
	EnumeratorsService,
	MessageService,
    KeycloakService,
    SpinnerService,
    {provide: OWL_DATE_TIME_LOCALE, useValue: 'pt'}/*,
    {
      provide: APP_INITIALIZER,
      useFactory: initializer,
      multi: true,
      deps: [KeycloakService]
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: RequestInterceptor,
      multi: true
    }*/
  ],
  entryComponents: [
    ConfirmDeleteDialogComponent
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }


