//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entities.module.spec.ts.p.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { EntitiesModule } from './entities.module';

describe('EntitiesModule', () => {
  let entitiesModule: EntitiesModule;

  beforeEach(() => {
    entitiesModule = new EntitiesModule();
  });

  it('should create an instance', () => {
    expect(entitiesModule).toBeTruthy();
  });
});
