//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity.module.spec.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { EmpresaModule } from './empresa.module';

describe('EmpresaModule', () => {
  let empresaModule: EmpresaModule;

  beforeEach(() => {
    empresaModule = new EmpresaModule();
  });

  it('should create an instance', () => {
    expect(empresaModule).toBeTruthy();
  });
});
