/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/service/endpoint/Endpoint.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.service.endpoint;

import java.util.List;
import java.util.stream.Collectors;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.ws.rs.Path;

import br.jus.framework.piloto.dao.EmpresaDao;
import br.jus.framework.piloto.domain.Empresa;
import br.jus.framework.piloto.manager.EmpresaManager;
import br.jus.framework.piloto.service.resource.EmpresaResource;
import br.jus.framework.service.impl.BaseEntityResourceEndpointImpl;

/**
 * A simple Endpoint for Empresa.
 */
@Stateless
@Path("/Empresa")
public class EmpresaEndpoint extends BaseEntityResourceEndpointImpl<Long, Empresa, EmpresaResource, EmpresaDao, EmpresaManager> {

    private static final long serialVersionUID = 1L;

    public EmpresaEndpoint() {
        super(Long.class, Empresa.class, EmpresaResource.class);
    }

    @Override
    @Inject
    protected void setManager(EmpresaManager manager) {
        super.setManager(manager);
    }

    @Override
    @Inject
    protected void setSearch(EmpresaDao search) {
        super.setSearch(search);
    }

    @Override
    public EmpresaResource toResource(Empresa entity, EmpresaResource resource, int depth) {
        resource = super.toResource(entity, resource, depth);
        if (resource != null) {
            resource.setVersaoEntidade(entity.getVersaoEntidade());
            resource.setDhCriacao(entity.getDhCriacao());
            resource.setDhModificacao(entity.getDhModificacao());
            resource.setFlHabilitado(entity.getFlHabilitado());
            resource.setNmLogin(entity.getNmLogin());
            resource.setCodigo(entity.getCodigo());
            resource.setNomeFantasia(entity.getNomeFantasia());
            resource.setRazaoSocial(entity.getRazaoSocial());
            resource.setNmLoginAlteracao(entity.getNmLoginAlteracao());
            if (depth-- > 0) {
                final int fdepth = depth;
            }
        }
        return resource;
    }

    /**
     * Converts the passed dto to a Empresa.
     * Convenient for query by example.
     */
    public Empresa fromResource(EmpresaResource resource, Empresa entity, int depth) {
        entity = super.fromResource(resource, entity, depth);
        if (entity != null) {
            entity.setVersaoEntidade(resource.getVersaoEntidade());
            entity.setDhCriacao(resource.getDhCriacao());
            entity.setDhModificacao(resource.getDhModificacao());
            entity.setFlHabilitado(resource.getFlHabilitado());
            entity.setNmLogin(resource.getNmLogin());
            entity.setCodigo(resource.getCodigo());
            entity.setNomeFantasia(resource.getNomeFantasia());
            entity.setRazaoSocial(resource.getRazaoSocial());
            entity.setNmLoginAlteracao(resource.getNmLoginAlteracao());
            if (depth-- > 0) {
            }
        }
        return entity;
    }
}