/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template celerio-pack-backend:src/main/java/service/endpoint/Endpoint.java.e.vm
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package br.jus.framework.piloto.service.endpoint;

import java.util.List;
import java.util.stream.Collectors;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.ws.rs.Path;

import br.jus.framework.piloto.dao.FilialDao;
import br.jus.framework.piloto.domain.Filial;
import br.jus.framework.piloto.manager.FilialManager;
import br.jus.framework.piloto.service.resource.FilialResource;
import br.jus.framework.service.impl.BaseEntityResourceEndpointImpl;

/**
 * A simple Endpoint for Filial.
 */
@Stateless
@Path("/Filial")
public class FilialEndpoint extends BaseEntityResourceEndpointImpl<Long, Filial, FilialResource, FilialDao, FilialManager> {

    private static final long serialVersionUID = 1L;

    @Inject
    private EmpresaEndpoint empresaEndpoint;

    public FilialEndpoint() {
        super(Long.class, Filial.class, FilialResource.class);
    }

    @Override
    @Inject
    protected void setManager(FilialManager manager) {
        super.setManager(manager);
    }

    @Override
    @Inject
    protected void setSearch(FilialDao search) {
        super.setSearch(search);
    }

    @Override
    public FilialResource toResource(Filial entity, FilialResource resource, int depth) {
        resource = super.toResource(entity, resource, depth);
        if (resource != null) {
            resource.setVersaoEntidade(entity.getVersaoEntidade());
            resource.setDhCriacao(entity.getDhCriacao());
            resource.setDhModificacao(entity.getDhModificacao());
            resource.setFlHabilitado(entity.getFlHabilitado());
            resource.setNmLogin(entity.getNmLogin());
            resource.setCodigo(entity.getCodigo());
            resource.setNomeFantasia(entity.getNomeFantasia());
            resource.setRazaoSocial(entity.getRazaoSocial());
            resource.setNmLoginAlteracao(entity.getNmLoginAlteracao());
            if (depth-- > 0) {
                final int fdepth = depth;
                resource.setIdEmpresa(empresaEndpoint.toResource(entity.getIdEmpresa(), depth));
            }
        }
        return resource;
    }

    /**
     * Converts the passed dto to a Filial.
     * Convenient for query by example.
     */
    public Filial fromResource(FilialResource resource, Filial entity, int depth) {
        entity = super.fromResource(resource, entity, depth);
        if (entity != null) {
            entity.setVersaoEntidade(resource.getVersaoEntidade());
            entity.setDhCriacao(resource.getDhCriacao());
            entity.setDhModificacao(resource.getDhModificacao());
            entity.setFlHabilitado(resource.getFlHabilitado());
            entity.setNmLogin(resource.getNmLogin());
            entity.setCodigo(resource.getCodigo());
            entity.setNomeFantasia(resource.getNomeFantasia());
            entity.setRazaoSocial(resource.getRazaoSocial());
            entity.setNmLoginAlteracao(resource.getNmLoginAlteracao());
            if (depth-- > 0) {
                entity.setIdEmpresa(empresaEndpoint.fromResource(resource.getIdEmpresa(), entity.getIdEmpresa(), depth));
            }
        }
        return entity;
    }
}