//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template celerio-pack-frontend:src/app/entities/entity/entity-list/entity-list.component.ts.e.vm
// Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
//
import { Component, Input } from '@angular/core';
import { EntityListComponent } from '../../../framework/components/entity-list.component';
import { Router } from '@angular/router';
import { MessageService } from '../../../util/message.service';
import { MatDialog } from '@angular/material';
import { FilterMetadata } from '../../../framework/service/paging/filtermetadata';
import { Operator } from '../../../framework/service/paging/operator';
import { Usuario } from '../usuario';
import { UsuarioService } from '../usuario.service';
import { UsuarioDataSource } from '../usuario.datasource';

@Component({
  selector: 'app-usuario-list',
  templateUrl: './usuario-list.component.html',
  styleUrls: ['./usuario-list.component.scss']
})
export class UsuarioListComponent extends EntityListComponent<Usuario, UsuarioService> {


    constructor(protected router: Router,
        protected messageService: MessageService,
        protected confirmDeleteDialog: MatDialog,
        protected entityService: UsuarioService) {
        super(router, messageService, confirmDeleteDialog, entityService, 'Usuario');
        // inicialização do dataSource
        this.dataSource = new UsuarioDataSource(this.paginator, this.sort, this.entityService);
        // configura as colunas exibidas no datatable.
        this.displayedColumns = [
            'nome',
            'login',
            'email',
            'actions'
        ];
        // configura os campos de filtro
        this.filters['nome'] = new FilterMetadata(null, Operator.LI);
        this.filters['login'] = new FilterMetadata(null, Operator.LI);
        this.filters['email'] = new FilterMetadata(null, Operator.LI);
    }

}
